#:schema https://developers.openai.com/codex/config-schema.json
personality = "pragmatic"
model = "gpt-5.3-codex"
model_reasoning_effort = "medium"

[tui]
status_line = [
  "codex-version",
  "model-name",
  "model-with-reasoning",
  "current-dir",
  "project-root",
  "git-branch",
  "context-used",
  "context-window-size",
  "five-hour-limit",
  "weekly-limit",
]

[features]
use_linux_sandbox_bwrap = true
collab = true
apps = true
